In [1]:
import pandas as pd

/Users/nikkosiegfried/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/nikkosiegfried/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

In [17]:
pd.set_option('display.max_columns', None)

In [2]:
df_names = pd.read_csv("data/name.basics.tsv.gz", compression='gzip', delimiter='\t')

In [6]:
df_crew = pd.read_csv("data/title.crew.tsv.gz", compression='gzip', delimiter='\t')

In [3]:
df = pd.read_csv('FINAL_DATA/Film_Locations_Geocoded_FINAL.csv')

In [9]:
#Extract only rows corresponding to focus data
unique_tconst = list(df.tconst.unique())
df_crew =  df_crew[df_crew['tconst'].isin(unique_tconst)]

In [19]:
nconst_list = []
for index, row in df_crew.iterrows():
    directors = row['directors'].split(',')
    writers = row['writers'].split(',')
    nconst_list.extend(directors)
    nconst_list.extend(writers)

In [20]:
nconst_df = pd.DataFrame(nconst_list, columns=['nconst'])

In [21]:
nconst_list = list(nconst_df.nconst.unique())

In [23]:
df_names = df_names[df_names['nconst'].isin(nconst_list)]

In [42]:
for index, row in df_names.iterrows():
    professions = row['primaryProfession']
    professions = professions.replace(',',', ')
    professions = professions.replace('_',' ')
    professions = professions.title()
    df_names.at[index, 'primaryProfession'] = professions

In [26]:
names_dict = {}
for index, row in df_names.iterrows():
    nconst = row['nconst']
    names_dict[nconst]=row['primaryName']

In [28]:
#put each director in its own row and get names from names_dict
for index, row in df_crew.iterrows():
    directors = row['directors'].split(',')
    try:
        if len(directors) == 1:
            df_crew.at[index, 'director1_nconst'] = directors[0]
            df_crew.at[index, 'director1_name'] = names_dict[directors[0]]        
        elif len(directors) > 1:
            df_crew.at[index, 'director1_nconst'] = directors[0]
            df_crew.at[index, 'director2_nconst'] = directors[1]
            df_crew.at[index, 'director1_name'] = names_dict[directors[0]]  
            df_crew.at[index, 'director2_name'] = names_dict[directors[1]]  
    except:
        continue

In [36]:
#put each writer in its own row and get names from names_dict
for index, row in df_crew.iterrows():
    writers = row['writers'].split(',')
    try:
        if len(writers) == 1:
            df_crew.at[index, 'writer1_nconst'] = writers[0]
            df_crew.at[index, 'writer1_name'] = names_dict[writers[0]]        
        elif len(writers) == 2:
            df_crew.at[index, 'writer1_nconst'] = writers[0]
            df_crew.at[index, 'writer2_nconst'] = writers[1]
            df_crew.at[index, 'writer1_name'] = names_dict[writers[0]]  
            df_crew.at[index, 'writer2_name'] = names_dict[writers[1]]  
        elif len(writers) > 2:
            df_crew.at[index, 'writer1_nconst'] = writers[0]
            df_crew.at[index, 'writer2_nconst'] = writers[1]
            df_crew.at[index, 'writer3_nconst'] = writers[2]
            df_crew.at[index, 'writer1_name'] = names_dict[writers[0]]  
            df_crew.at[index, 'writer2_name'] = names_dict[writers[1]]  
            df_crew.at[index, 'writer3_name'] = names_dict[writers[2]]  
    except:
        continue

In [46]:
crew_dict = {}
for index, row in df_crew.iterrows():
    tconst = row['tconst']
    crew_dict[tconst] = {}
    crew_dict[tconst]['director1_nconst']=row['director1_nconst']
    crew_dict[tconst]['director1_name']=row['director1_name']
    crew_dict[tconst]['director2_nconst']=row['director2_nconst']
    crew_dict[tconst]['director2_name']=row['director2_name']
    crew_dict[tconst]['writer1_nconst']=row['writer1_nconst']
    crew_dict[tconst]['writer1_name']=row['writer1_name']
    crew_dict[tconst]['writer2_nconst']=row['writer2_nconst']
    crew_dict[tconst]['writer2_name']=row['writer2_name']
    crew_dict[tconst]['writer3_nconst']=row['writer3_nconst']
    crew_dict[tconst]['writer3_name']=row['writer3_name']

In [50]:
for index, row in df.iterrows():
    tconst = row['tconst']
    try:
        df.at[index, 'director1_nconst'] = crew_dict[tconst]['director1_nconst']
        df.at[index, 'director1_name'] = crew_dict[tconst]['director1_name']
        df.at[index, 'director2_nconst'] = crew_dict[tconst]['director2_nconst']
        df.at[index, 'director2_name'] = crew_dict[tconst]['director2_name']
        df.at[index, 'writer1_nconst'] = crew_dict[tconst]['writer1_nconst']
        df.at[index, 'writer1_name'] = crew_dict[tconst]['writer1_name']
        df.at[index, 'writer2_nconst'] = crew_dict[tconst]['writer2_nconst']
        df.at[index, 'writer2_name'] = crew_dict[tconst]['writer2_name']
        df.at[index, 'writer3_nconst'] = crew_dict[tconst]['writer3_nconst']
        df.at[index, 'writer3_name'] = crew_dict[tconst]['writer3_name']
    except:
        continue

In [53]:
#get unique titles
titles_list = []
for index, row in df_names.iterrows():
    titles = row['knownForTitles'].split(',')
    titles_list.extend(titles)

titles_df = pd.DataFrame(titles_list, columns=['title'])
titles_list = list(titles_df.title.unique())
titles_list

['tt0054215',
 'tt0053125',
 'tt0052357',
 'tt0056869',
 'tt0033467',
 'tt0052311',
 'tt0040525',
 'tt0057427',
 'tt0079522',
 'tt0075686',
 'tt0118954',
 'tt0091167',
 'tt1630029',
 'tt0499549',
 'tt0090605',
 'tt0103064',
 'tt0080749',
 'tt0077651',
 'tt0069945',
 'tt0082340',
 'tt0032553',
 'tt0027977',
 'tt0044837',
 'tt0021749',
 'tt1205489',
 'tt0405159',
 'tt0186566',
 'tt0105695',
 'tt0367279',
 'tt0075213',
 'tt0268978',
 'tt0112384',
 'tt0119822',
 'tt0117998',
 'tt0103484',
 'tt0455805',
 'tt0076759',
 'tt0066434',
 'tt0069704',
 'tt0082971',
 'tt0108052',
 'tt0083866',
 'tt0120815',
 'tt0091763',
 'tt0102138',
 'tt0110632',
 'tt0096969',
 'tt0010781',
 'tt0030778',
 'tt0006213',
 'tt0030738',
 'tt0094012',
 'tt0395251',
 'tt0082517',
 'tt0071230',
 'tt0099487',
 'tt1142977',
 'tt0121164',
 'tt0408236',
 'tt0078788',
 'tt0071360',
 'tt0068646',
 'tt0071562',
 'tt0107290',
 'tt0070909',
 'tt0108757',
 'tt0086984',
 'tt0080661',
 'tt0099165',
 'tt0094226',
 'tt1441912',
 'tt0308055',
 'tt3294746',
 'tt0100994',
 'tt0103772',
 'tt0114436',
 'tt0108162',
 'tt0118577',
 'tt0114369',
 'tt0443706',
 'tt2267998',
 'tt1285016',
 'tt0093748',
 'tt0098554',
 'tt0088847',
 'tt0090305',
 'tt0107156',
 'tt0190332',
 'tt0454876',
 'tt0808357',
 'tt0077405',
 'tt0069762',
 'tt0478304',
 'tt5827916',
 'tt0117218',
 'tt0086960',
 'tt0443489',
 'tt0094898',
 'tt0092007',
 'tt0102975',
 'tt0796366',
 'tt0088170',
 'tt0116250',
 'tt0095647',
 'tt0077928',
 'tt0092563',
 'tt0042192',
 'tt0041587',
 'tt0056937',
 'tt0069281',
 'tt0082096',
 'tt0089092',
 'tt0088323',
 'tt0114069',
 'tt0087332',
 'tt0107048',
 'tt0083131',
 'tt0478311',
 'tt0109830',
 'tt0105046',
 'tt0117438',
 'tt0117666',
 'tt0120324',
 'tt0243133',
 'tt0285742',
 'tt0452594',
 'tt0396269',
 'tt1078940',
 'tt5657856',
 'tt0093870',
 'tt0389557',
 'tt3716530',
 'tt0164052',
 'tt0093191',
 'tt27503384',
 'tt0087884',
 'tt0101458',
 'tt0067992',
 'tt0072431',
 'tt0063462',
 'tt0075223',
 'tt0088763',
 'tt0118884',
 'tt1907668',
 'tt0205655',
 'tt0065278',
 'tt0069599',
 'tt0096108',
 'tt0112722',
 'tt0298814',
 'tt0137494',
 'tt0100822',
 'tt0272338',
 'tt0118749',
 'tt0469494',
 'tt11271038',
 'tt0454776',
 'tt0384766',
 'tt0095243',
 'tt0157583',
 'tt0061811',
 'tt0067185',
 'tt0078841',
 'tt0070290',
 'tt0120591',
 'tt1055369',
 'tt2109248',
 'tt0117500',
 'tt0079417',
 'tt0061418',
 'tt0078346',
 'tt0087921',
 'tt0108724',
 'tt0124198',
 'tt0110308',
 'tt1091191',
 'tt0029852',
 'tt0038370',
 'tt0036430',
 'tt0034862',
 'tt0067328',
 'tt0063671',
 'tt0070510',
 'tt0079843',
 'tt0093209',
 'tt0082348',
 'tt0120706',
 'tt0068473',
 'tt1542344',
 'tt0289043',
 'tt0111149',
 'tt1010048',
 'tt0780504',
 'tt0092699',
 'tt0101698',
 'tt0089504',
 'tt0077416',
 'tt0067756',
 'tt0080855',
 'tt0090350',
 'tt0241527',
 'tt0295297',
 'tt1454029',
 'tt0294870',
 'tt0056687',
 'tt0037913',
 'tt0042376',
 'tt0046446',
 'tt0097662',
 'tt0128442',
 'tt0105226',
 'tt0100944',
 'tt0062512',
 'tt0062803',
 'tt0093260',
 'tt0087363',
 'tt0082533',
 'tt0122718',
 'tt0049833',
 'tt0044672',
 'tt0043014',
 'tt0041838',
 'tt0089457',
 'tt0839995',
 'tt0093409',
 'tt0075066',
 'tt0084865',
 'tt0072081',
 'tt0051301',
 'tt0120484',
 'tt0185431',
 'tt0120888',
 'tt0142342',
 'tt0381061',
 'tt0059800',
 'tt0055928',
 'tt0086006',
 'tt0056218',
 'tt0116654',
 'tt0058576',
 'tt0119189',
 'tt0090180',
 'tt0067116',
 'tt0070047',
 'tt0080569',
 'tt0064115',
 'tt0074119',
 'tt0093779',
 'tt0074860',
 'tt0040724',
 'tt0053221',
 'tt0061619',
 'tt0056059',
 'tt0083511',
 'tt0103644',
 'tt0088194',
 'tt0040897',
 'tt0071315',
 'tt0042208',
 'tt0089841',
 'tt0086837',
 'tt0082869',
 'tt0111438',
 'tt0120004',
 'tt0095953',
 'tt0101516',
 'tt0120885',
 'tt1933667',
 'tt0092593',
 'tt0051378',
 'tt0071733',
 'tt0080388',
 'tt0387914',
 'tt0225071',
 'tt0280380',
 'tt2062575',
 'tt0095016',
 'tt0246894',
 'tt0107362',
 'tt0093773',
 'tt0082031',
 'tt0078721',
 'tt0076161',
 'tt0061391',
 'tt0317910',
 'tt0119107',
 'tt0096257',
 'tt0896866',
 'tt0109831',
 'tt0330373',
 'tt0119008',
 'tt0104522',
 'tt0061722',
 'tt0376541',
 'tt0061184',
 'tt0115685',
 'tt6053438',
 'tt11196036',
 'tt0118564',
 'tt0075314',
 'tt0293508',
 'tt0118688',
 'tt0134273',
 'tt0183649',
 'tt0421054',
 'tt0477080',
 'tt0092099',
 'tt0108399',
 'tt0259288',
 'tt1741225',
 'tt0109040',
 'tt0363589',
 'tt0842929',
 'tt0097240',
 'tt0102494',
 'tt0311113',
 'tt1023114',
 'tt0090329',
 'tt0097165',
 'tt0092890',
 'tt0149439',
 'tt0085655',
 'tt0107065',
 'tt0343818',
 'tt0182789',
 'tt0079945',
 'tt0804484',
 'tt0110932',
 'tt0109635',
 'tt0120184',
 'tt0102592',
 'tt0313443',
 'tt0112857',
 'tt13207736',
 'tt0068655',
 'tt0054949',
 'tt0099669',
 'tt0242775',
 'tt0028950',
 'tt0019558',
 'tt0009937',
 'tt1403981',
 'tt0427969',
 'tt0141842',
 'tt0914387',
 'tt5071412',
 'tt1856010',
 'tt0944947',
 'tt0088513',
 'tt0086759',
 'tt0092312',
 'tt0349358',
 'tt0118150',
 'tt0368008',
 'tt0488120',
 'tt0164184',
 'tt0045810',
 'tt0010185',
 'tt0013540',
 'tt0029516',
 'tt0402711',
 'tt3205802',
 'tt11238096',
 'tt0118254',
 'tt0313542',
 'tt2364841',
 'tt0465538',
 'tt1547234',
 'tt0433309',
 'tt0120596',
 'tt0282695',
 'tt0101272',
 'tt0107688',
 'tt0970411',
 'tt17491088',
 'tt7203552',
 'tt0386676',
 'tt2188671',
 'tt0115639',
 'tt0118880',
 'tt7975244',
 'tt0187078',
 'tt0109982',
 'tt0138801',
 'tt0147070',
 'tt0107763',
 'tt0202695',
 'tt0443527',
 'tt1174042',
 'tt0377029',
 'tt0863046',
 'tt0141109',
 'tt2089826',
 'tt0088925',
 'tt0083557',
 'tt0412175',
 'tt0090021',
 'tt0285333',
 'tt0306414',
 'tt7462410',
 'tt4574334',
 'tt15384586',
 'tt3455542',
 'tt32513080',
 'tt6598282',
 'tt10294634',
 'tt0313043',
 'tt3514324',
 'tt2654580',
 'tt0139134',
 'tt2963232',
 'tt1376213',
 'tt0187559',
 'tt5649144',
 'tt0185906',
 'tt0096754',
 'tt3230854',
 'tt0264235',
 'tt0175844',
 'tt0435651',
 'tt0364151',
 'tt0086197',
 'tt1049951',
 'tt14953612',
 'tt1266020',
 'tt0838283',
 'tt11057302',
 'tt11280740',
 'tt0282209',
 'tt0099044',
 'tt0176269',
 'tt0108358',
 'tt1190634',
 'tt2403776',
 'tt1520211',
 'tt10623646',
 'tt0097351',
 'tt0105435',
 'tt0213668',
 'tt0081873',
 'tt0090466',
 'tt0106079',
 'tt0112086',
 'tt0088944',
 'tt0376994',
 'tt0242445',
 'tt1600199',
 'tt1074206',
 'tt5500158',
 'tt5555260',
 'tt1219024',
 'tt0995832',
 'tt2006120',
 'tt0088247',
 'tt1340138',
 'tt0177991',
 'tt0395843',
 'tt0116908',
 'tt0882977',
 'tt3920596',
 'tt0118437',
 'tt0172493',
 'tt0088527',
 'tt0117882',
 'tt0350258',
 'tt7125860',
 'tt10696784',
 'tt0385307',
 'tt3315342',
 'tt0265459',
 'tt0104694',
 'tt0151738',
 'tt0100405',
 'tt0791304',
 'tt0094812',
 'tt0329717',
 'tt0117918',
 'tt0105812',
 'tt0106611',
 'tt0114924',
 'tt0117333',
 'tt0368891',
 'tt0264796',
 'tt0099685',
 'tt3076658',
 'tt0075148',
 'tt0165929',
 'tt0111257',
 'tt0419706',
 'tt0115285',
 'tt0118464',
 'tt0055031',
 'tt0061735',
 'tt0053946',
 'tt0051525',
 'tt0465602',
 'tt1385867',
 'tt0329101',
 'tt0337619',
 'tt0091860',
 'tt30947718',
 'tt0108026',
 'tt0216216',
 'tt0096098',
 'tt0472562',
 'tt0076843',
 'tt0076095',
 'tt0098384',
 'tt0093936',
 'tt0091129',
 'tt0080934',
 'tt0089155',
 'tt0138097',
 'tt1412386',
 'tt0377107',
 'tt2555736',
 'tt0177215',
 'tt3242934',
 'tt0098780',
 'tt7315982',
 'tt0790736',
 'tt0106697',
 'tt0285331',
 'tt1399045',
 'tt2070791',
 'tt0130018',
 'tt4085584',
 'tt0159206',
 'tt11875316',
 'tt6453190',
 'tt0364961',
 'tt5157426',
 'tt1326270',
 'tt1592254',
 'tt0399877',
 'tt0158187',
 'tt0224503',
 'tt0783338',
 'tt0089569',
 'tt0101452',
 'tt0112205',
 'tt0081259',
 'tt0100403',
 'tt0113492',
 'tt2707408',
 'tt0321021',
 'tt0364845',
 'tt0200276',
 'tt0804503',
 'tt1714204',
 'tt2402061',
 'tt1001558',
 'tt0116277',
 'tt0811124',
 'tt19396760',
 'tt0212208',
 'tt9243946',
 'tt0118665',
 'tt0120684',
 'tt8068860',
 'tt0129290',
 'tt4944916',
 'tt7417858',
 'tt0335007',
 'tt4978710',
 'tt3726704',
 'tt5259822',
 'tt0103706',
 'tt0109758',
 'tt0335163',
 'tt0179128',
 'tt0127328',
 'tt0101590',
 'tt0092420',
 'tt0094450',
 'tt0112051',
 'tt0104321',
 'tt0113101',
 'tt0173390',
 'tt0245501',
 'tt0261983',
 'tt0361862',
 'tt0800241',
 'tt1772264',
 'tt0020629',
 'tt0040506',
 'tt0051207',
 'tt0119643',
 'tt0114180',
 'tt0238784',
 'tt1843678',
 'tt1305587',
 'tt5458820',
 'tt0499596',
 'tt0246578',
 'tt0357413',
 'tt0898332',
 'tt0162346',
 'tt0307987',
 'tt2990138',
 'tt3021498',
 'tt2761354',
 'tt0452631',
 'tt4192782',
 'tt14418052',
 'tt0179116',
 'tt11691774',
 'tt11379456',
 'tt3749900',
 'tt8425532',
 'tt0379623',
 'tt8712618',
 'tt1728102',
 'tt0117247',
 'tt0094484',
 'tt0067535',
 'tt0066450',
 'tt3458776',
 'tt0257725',
 'tt10883362',
 'tt0486531',
 'tt2357547',
 'tt4855114',
 'tt1837654',
 'tt0280287',
 'tt0203259',
 'tt0275140',
 'tt1582459',
 'tt3032476',
 'tt0213327',
 'tt0106179',
 'tt13623126',
 'tt4288182',
 'tt14271498',
 'tt10584608',
 'tt0362989',
 'tt0357567',
 'tt0270688',
 'tt0340147',
 'tt1595859',
 'tt5171438',
 'tt3743822',
 'tt0368479',
 'tt0082177',
 'tt0035032',
 'tt0053271',
 'tt0037908',
 'tt0038339',
 'tt0091323',
 'tt5481572',
 'tt0159594',
 'tt20227114',
 'tt0119738',
 'tt0120889',
 'tt0042539',
 'tt0043660',
 'tt0045669',
 'tt0037024',
 'tt0098844',
 'tt1836195',
 'tt2427220',
 'tt0247199',
 'tt0430912',
 'tt0425308',
 'tt0104073',
 'tt0048907',
 'tt0058810',
 'tt0101065',
 'tt5788792',
 'tt4889096',
 'tt5212822',
 'tt0813715',
 'tt1462059',
 'tt5511582',
 'tt0115857',
 'tt0090728',
 'tt0100514',
 'tt0104291',
 'tt3487410',
 'tt8390342',
 'tt5164196',
 'tt14449470',
 'tt2193021',
 'tt1842530',
 'tt6473344',
 'tt0113987',
 'tt1127893',
 'tt0411008',
 'tt9813792',
 'tt0103956',
 'tt8064302',
 'tt7569576',
 'tt8740790',
 'tt0460627',
 'tt0098382',
 'tt0084726',
 'tt2137109',
 'tt0759482',
 'tt5348176',
 'tt2575988',
 'tt0312528',
 'tt5164432',
 'tt10166602',
 'tt6462958',
 'tt0104265',
 'tt0260866',
 'tt0209557',
 'tt1202220',
 'tt8550800',
 'tt8697870',
 'tt0114857',
 'tt0455960',
 'tt0111323',
 'tt0257756',
 'tt0324619',
 'tt0104376',
 'tt0243595',
 'tt2249007',
 'tt0117381',
 'tt0193676',
 'tt2404463',
 'tt0110006',
 'tt3079380',
 'tt17220216',
 'tt4229954',
 'tt0244365',
 'tt1013753',
 'tt1998372',
 'tt1616195',
 'tt0370984',
 'tt0112167',
 'tt0115320',
 'tt0106057',
 'tt0491522',
 'tt0042286',
 'tt0046816',
 'tt0034739',
 'tt0255653',
 'tt0206420',
 'tt2103264',
 'tt0365907',
 'tt0765120',
 'tt0090568',
 'tt3813018',
 'tt0116683',
 'tt8201170',
 'tt0090103',
 'tt0097576',
 'tt0085407',
 'tt0117331',
 'tt0034587',
 'tt0036733',
 'tt0036341',
 'tt0055796',
 'tt0046911',
 'tt0053459',
 'tt0116095',
 'tt0118169',
 'tt1606375',
 'tt0408381',
 'tt0097963',
 'tt2103281',
 'tt3450958',
 'tt0335121',
 'tt1386703',
 'tt0056848',
 'tt0453372',
 'tt0086825',
 'tt1593748',
 'tt0064490',
 'tt0066413',
 'tt29195147',
 'tt0054986',
 'tt0110390',
 'tt0131369',
 'tt0493181',
 'tt3627322',
 'tt0050212',
 'tt0133152',
 'tt0063442',
 'tt0068408',
 'tt0077031',
 'tt0083486',
 'tt0760142',
 'tt0088559',
 'tt0758745',
 'tt0348914',
 'tt1064899',
 'tt0999913',
 'tt1073241',
 'tt2005374',
 'tt0762139',
 'tt0111001',
 'tt1531930',
 'tt0316110',
 'tt0239195',
 'tt0271894',
 'tt0118440',
 'tt0119174',
 'tt0113957',
 'tt0181852',
 'tt0986263',
 'tt0113986',
 'tt6802308',
 'tt0216522',
 'tt0118612',
 'tt0351977',
 'tt0278295',
 'tt7660850',
 'tt0093777',
 'tt0097179',
 'tt0082951',
 'tt0286486',
 'tt0098944',
 'tt0094561',
 'tt0037059',
 'tt0047762',
 'tt0045171',
 'tt0041590',
 'tt0050579',
 'tt0202179',
 'tt0069732',
 'tt0076983',
 'tt0369294',
 'tt0496424',
 'tt1839578',
 'tt7211618',
 'tt6038954',
 'tt7320300',
 'tt5706996',
 'tt1411956',
 'tt0089612',
 'tt0985040',
 'tt0119019',
 'tt4572984',
 'tt4456776',
 'tt0210634',
 'tt0208102',
 'tt5822812',
 'tt5580540',
 'tt1691917',
 'tt2666270',
 'tt0079116',
 'tt0047780',
 'tt0042074',
 'tt0017925',
 'tt0015324',
 'tt0015163',
 'tt0014341',
 'tt0078566',
 'tt0070992',
 'tt0081896',
 'tt0077003',
 'tt0031679',
 'tt0033712',
 'tt0035417',
 'tt2802850',
 'tt0903747',
 'tt0275832',
 'tt0400497',
 'tt0064603',
 'tt0076137',
 'tt0046593',
 'tt1488589',
 'tt0437745',
 'tt0166896',
 'tt1020990',
 'tt0107131',
 'tt0057180',
 'tt0116552',
 'tt0341874',
 'tt0092492',
 'tt0088000',
 'tt2381931',
 'tt0100151',
 'tt0119630',
 'tt0093477',
 'tt0073172',
 'tt0134630',
 'tt0087980',
 'tt0080854',
 'tt0247638',
 'tt0396652',
 'tt0368933',
 'tt19796842',
 'tt4396558',
 'tt9642010',
 'tt12663898',
 'tt0095744',
 'tt0029606',
 'tt0047522',
 'tt0033836',
 'tt0035415',
 'tt0042991',
 'tt0074512',
 'tt0061277',
 'tt0066365',
 'tt0247082',
 'tt1319636',
 'tt10155932',
 'tt2531344',
 'tt2848292',
 'tt0296166',
 'tt8778064',
 'tt4419214',
 'tt10329042',
 'tt0088821',
 'tt0090915',
 'tt4844140',
 'tt0077631',
 'tt0080492',
 'tt0084021',
 'tt0088395',
 'tt1333125',
 'tt1114740',
 'tt0317303',
 'tt0195945',
 'tt0043208',
 'tt0053547',
 'tt0443295',
 'tt0073955',
 'tt0111280',
 'tt1842329',
 'tt0120570',
 'tt1844080',
 'tt0393162',
 'tt0098789',
 'tt0206275',
 'tt0119664',
 'tt0096697',
 'tt1826940',
 'tt0913742',
 'tt0054988',
 'tt0051744',
 'tt0063522',
 'tt0094924',
 'tt0386792',
 'tt0105080',
 'tt0165003',
 'tt0115167',
 'tt1242441',
 'tt1441142',
 'tt9770286',
 'tt10720352',
 'tt16431870',
 'tt0115305',
 'tt0218616',
 'tt3960394',
 'tt0354899',
 'tt0250223',
 'tt0118976',
 'tt1667889',
 'tt8080122',
 'tt4301160',
 'tt1119644',
 'tt0093640',
 'tt1082601',
 'tt0112173',
 'tt14926940',
 'tt0105151',
 'tt0176948',
 'tt7335184',
 'tt5024912',
 'tt1659337',
 'tt2543472',
 'tt2771200',
 'tt3922818',
 'tt0240890',
 'tt1626146',
 'tt0113133',
 'tt0040740',
 'tt0027845',
 'tt0023872',
 'tt0030783',
 'tt0189246',
 'tt0260897',
 'tt4675250',
 'tt0120172',
 'tt1117667',
 'tt0171311',
 'tt0089901',
 'tt0083978',
 'tt0075222',
 'tt0088275',
 'tt0030149',
 'tt0018203',
 'tt0023268',
 'tt0041172',
 'tt0018037',
 'tt0015191',
 'tt0123906',
 'tt0021442',
 'tt0419491',
 'tt0104850',
 'tt0093626',
 'tt0089892',
 'tt6983908',
 'tt10227282',
 'tt1436557',
 'tt0139030',
 ...]